<?php
$translate = Zend_Registry::get('Zend_Translate');

echo $this->doctype() ?>
<html lang="en">
<head>
	<meta charset="utf-8">
    <?php echo $this->headTitle() ?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
	<?php echo $this->JQuery() ?>

	<style type="text/css">
	body {
		padding-top: 60px;
		padding-bottom: 40px;
	}
	.sidebar-nav {
		padding: 9px 0;
	}
	</style>

	<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<a class="brand" href="#">ZF1 Skeleton Project</a>
				<div class="nav-collapse collapse">
					<p class="navbar-text pull-right">
						Logged in as <a href="#" class="navbar-link">Username</a>
					</p>
					<ul class="nav">
						<li class="active"><a href="#">Home</a></li>
						<li><a href="#about">About</a></li>
						<li><a href="#contact">Contact</a></li>
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</div>
	</div>

	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span3">
				<div class="well sidebar-nav">
					<ul class="nav nav-list">
						<li class="nav-header"><?php echo $translate->_("Documentation"); ?></li>
						<li class="active"><a href="http://framework.zend.com/manual/1.12" target="_blank"><?php echo $translate->_("Zend Framework Reference"); ?></a></li>
						<li><a href="http://docs.jquery.com/" target="_blank"><?php echo $translate->_("jQuery Documentation"); ?></a></li>
						<li><a href="http://twitter.github.com/bootstrap/getting-started.html" target="_blank"><?php echo $translate->_("Twitter Bootstrap"); ?></a></li>
						<li class="nav-header"><?php echo $translate->_("Sidebar"); ?></li>
						<li><a href="#"><?php echo $translate->_("Link"); ?></a></li>
						<li><a href="#"><?php echo $translate->_("Link"); ?></a></li>
						<li><a href="#"><?php echo $translate->_("Link"); ?></a></li>
						<li class="nav-header"><?php echo $translate->_("Language"); ?></li>
						<li>
							<form action="#" id="language-form" method="get">
								<select name="lang" onchange="$('#language-form').submit()">
									<option value="en"<?php echo ($translate->getLocale() == 'en' ? ' selected="selected"' : ''); ?>><?php echo $translate->_("English (US)"); ?></option>
									<option value="fr"<?php echo ($translate->getLocale() == 'fr' ? ' selected="selected"' : ''); ?>><?php echo $translate->_("French"); ?></option>
								</select>
							</form>
						</li>
					</ul>
				</div><!--/.well -->
			</div><!--/span-->
			<div class="span9">
				<?php echo $this->layout()->content ?>
			</div><!--/span-->
		</div><!--/row-->

		<hr>

		<footer>
			<p>Copyright &copy; <?php echo date('Y'); ?> ZF Developer</p>
		</footer>

	</div><!--/.fluid-container-->
</body>
</html>